#RECAPTCHA_PRIVATE_KEY = '6Lfvs88SAAAAAGa198oiiS6gO-GDkLCdVMjLKksZ'
#RECAPTCHA_PUBLIC_KEY = '6Lfvs88SAAAAAN14X5JDXVOYvbnZhdXDY1EFCgzW'
#RECAPTCHA_REMOTE_IP = '174.129.75.103'
#RECAPTCHA_VERIFY_URL = 'http://www.google.com/recaptcha/api/verify'


RECAPTCHA_PRIVATE_KEY = '6Lc3tM8SAAAAANp0sKMnL-K5qc1Fu_uHpDeiYo7S'
RECAPTCHA_PUBLIC_KEY = '6Lc3tM8SAAAAAGwjoAKevUEYnbPMZ0dZhUi2CUoI'
RECAPTCHA_REMOTE_IP = '127.0.0.1'
RECAPTCHA_VERIFY_URL = 'http://www.google.com/recaptcha/api/verify'