RECAPTCHA_PRIVATE_KEY = '6LeUR80SAAAAAHFGOMAxHZ0hpLmFjjpPA15gHePZ'
RECAPTCHA_PUBLIC_KEY = '6LeUR80SAAAAAIIbp6Dt8D1jfZrF3gkn3DN3mVUP'
RECAPTCHA_REMOTE_IP = '127.0.0.1'
RECAPTCHA_VERIFY_URL = 'http://www.google.com/recaptcha/api/verify'