source 'https://rubygems.org'

gem 'rails', '3.2.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
gem 'ruby-debug19', :require => 'ruby-debug'

# Typhoeus runs HTTP requests in parallel while cleanly encapsulating handling logic.
gem 'typhoeus'

# Twitter login
gem 'omniauth-twitter'

# Youtube upload
gem 'youtube_it'

# To use recaptcha
gem "recaptcha", '0.3.4', :require => "recaptcha/rails"

gem "uploadify_rails3"

gem "carrierwave", '0.5.8'
gem "rmagick", '2.13.1'
